# Generated by Django 4.2 on 2023-05-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_population', models.CharField(max_length=100)),
                ('white_alone', models.CharField(max_length=100)),
                ('black_or_african_american_alone', models.CharField(max_length=100)),
                ('american_indian_and_alaskan_native_alone', models.CharField(max_length=100)),
                ('asian_alone', models.CharField(max_length=100)),
                ('native_hawaiian_and_other_pacific_islander_alone', models.CharField(max_length=100)),
                ('other_race_alone', models.CharField(max_length=100)),
                ('geo_id', models.CharField(max_length=100)),
            ],
        ),
    ]
