# Generated by Django 4.2 on 2023-05-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(max_length=100)),
                ('people_insured', models.CharField(max_length=100)),
                ('people_not_insured', models.CharField(max_length=100)),
            ],
        ),
    ]
