# Generated by Django 4.2 on 2023-06-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poverty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_ages_in_poverty', models.CharField(max_length=100)),
                ('ages_5_to_17_in_poverty', models.CharField(max_length=100)),
                ('ages_0_17_in_poverty', models.CharField(max_length=100)),
            ],
        ),
    ]
