# Generated by Django 3.2.19 on 2023-08-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_populationbysex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationbysex',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=10),
        ),
    ]
