# Generated by Django 3.2.19 on 2023-08-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_populationbysex_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='populationbysex',
            old_name='Thirty_34_years',
            new_name='Thirty_to_34_years',
        ),
        migrations.RenameField(
            model_name='populationbysex',
            old_name='eighteen_19_years',
            new_name='eighteen_to_19_years',
        ),
        migrations.RenameField(
            model_name='populationbysex',
            old_name='fifteen_17_years',
            new_name='fifteen_to_17_years',
        ),
        migrations.RenameField(
            model_name='populationbysex',
            old_name='five_9_years',
            new_name='five_to_9_years',
        ),
        migrations.RenameField(
            model_name='populationbysex',
            old_name='ten_14_years',
            new_name='ten_to_14_years',
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=10, null=True),
        ),
    ]
