# Generated by Django 3.2.19 on 2023-09-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230831_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationbysex',
            name='Eighty_five_and_above',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='Eighty_to_84_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='Fifty_five_to_59',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='Fifty_to_54_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='Forty_Five_to_49',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='Forty_to_44_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='Thirty_Five_to_39',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='Thirty_to_34_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='Twenty_Five_to_29',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='Twenty_one_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='Twenty_two_to_24',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='Twenty_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='eighteen_to_19_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='fifteen_to_17_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='five_to_9_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='seventy_five_to_79',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='seventy_to_74_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='sixty_five_to_66',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='sixty_seven_to_69',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='sixty_to_61_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='sixty_two_to_64',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='ten_to_14_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='total_population',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='populationbysex',
            name='under_5_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
