# Generated by Django 3.2.19 on 2023-09-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230902_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopulationBySex',
        ),
    ]
