# Generated by Django 3.2.19 on 2023-09-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_populationbysex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopulationBySex',
        ),
    ]
