# Generated by Django 3.2.19 on 2023-09-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_populationbysex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedianIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Median_Income', models.CharField(max_length=100)),
                ('White_Alone', models.CharField(max_length=100)),
                ('Black_or_African_American', models.CharField(max_length=100)),
                ('American_Indian_and_Alaska_Native_Alone', models.CharField(max_length=100)),
                ('Asian_Alone', models.CharField(max_length=100)),
                ('Two_or_more_races', models.CharField(max_length=100)),
                ('Some_other_race_alone', models.CharField(max_length=100)),
                ('Hispanic_or_Latino', models.CharField(max_length=100)),
            ],
        ),
    ]
